import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Viewer } from '../components/viewer'
import { Button } from '../components/button'
import { useActionsStore } from '../stores/actions-store'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const addCube = useActionsStore(state => state.addCube) 
  const scene = useActionsStore(state => state.scene) 
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <Button onClick={addCube}>Add cube</Button>
      </nav>
      <main className={styles.main}>
         <Viewer/>
      </main>
    </>
  )
}
